ALTER TABLE "Propostas" ADD COLUMN IF NOT EXISTS "driveLink" VARCHAR(500);
ALTER TABLE "Contratos" ADD COLUMN IF NOT EXISTS "driveLink" VARCHAR(500);
ALTER TABLE "Documentos" ADD COLUMN IF NOT EXISTS "driveLink" VARCHAR(500);

